ProgrammingDaisukiClub/WPCS2

config/routes.rb, package.json
http://crypt.codemancers.com/posts/2016-03-18-rails-webpack-heroku/
=> Fix heroku settings for using TypeScript via WebPack.

Gemfile, Gemfile.lock, config/environments/development.rb, config/initializers/devise.rb, config/locales/devise.en.yml
=> Install devise

Gemfile, Gemfile.lock
そのうち必要になると思うのでgem追加しておきました
TO: 使ったことない人へ
`binding.pry`でブレークポイント埋め込めます
参考: http://qiita.com/AknYk416/items/6f0bec58712edaf4940e
=> pry-byebug

Gemfile, Gemfile.lock, app/controllers/users/confirmations_controller.rb, app/controllers/users/omniauth_callbacks_controller.rb, app/controllers/users/passwords_controller.rb, app/controllers/users/registrations_controller.rb, app/controllers/users/sessions_controller.rb, app/controllers/users/unlocks_controller.rb, app/models/user.rb, app/views/users/confirmations/new.html.erb, app/views/users/mailer/confirmation_instructions.html.erb, app/views/users/mailer/password_change.html.erb, app/views/users/mailer/reset_password_instructions.html.erb, app/views/users/mailer/unlock_instructions.html.erb, app/views/users/passwords/edit.html.erb, app/views/users/passwords/new.html.erb, app/views/users/registrations/edit.html.erb, app/views/users/registrations/new.html.erb, app/views/users/sessions/new.html.erb, app/views/users/shared/_links.html.erb, app/views/users/unlocks/new.html.erb, config/environments/development.rb, config/routes.rb, db/migrate/20170211042541_devise_create_users.rb, db/schema.rb, test/fixtures/users.yml, test/models/user_test.rb
Userモデル生成しました
登録時にメールアドレスの確認を行うようにしておきました
ユーザー名のカラムなどの追加は一旦後にしようと思います
(とりあえず、ユーザー認証ないと開発進めづらいし)
Viewは確実にカスタマイズすると思うので生成
正直使わない気もするけれど一応Controllerも生成しておきました
(不要なら消しちゃいます)
それから、開発環境でのメールの確認用にletter_opener_webというgemをインストールしてます
/letter_openerにアクセスすれば送信されたメールが確認できます
* 追加カラムのmigration/sanitizer
* 認証まわりのi18n対応
* スタイル整える
=> Generate devise user

.gitignore, logfile, package.json, src/tutorial/Hello.tsx, src/tutorial/index.tsx, tsconfig.json, tslint.json
- Add tslint using tslint-microsoft-contrib settings.
- Remove all tslint errors.
- Simplify tsconfig.
- Remove an unused file improving .gitignore.
とりあえず、tslintの設定はMS推奨版にしているけど、適宜、微調整していきたい。
=> Add tslint for consistent code. Close #23

app/models/contest.rb, app/models/contest_registration.rb, app/models/problem.rb, app/models/submission.rb, app/models/test_case.rb, db/migrate/20170212175124_create_contests.rb, db/migrate/20170212175310_create_problems.rb, db/migrate/20170212175352_create_test_cases.rb, db/migrate/20170212175408_create_submissions.rb, db/migrate/20170212175658_create_contest_registrations.rb, test/fixtures/contest_registrations.yml, test/fixtures/contests.yml, test/fixtures/problems.yml, test/fixtures/submissions.yml, test/fixtures/test_cases.yml, test/models/contest_registration_test.rb, test/models/contest_test.rb, test/models/problem_test.rb, test/models/submission_test.rb, test/models/test_case_test.rb
PR: #30 からブランチ切ってます
#30 がマージされたらマージしてください
一応、テーブルの一覧がIssue: #26 にあるのでそちらも参照しながらレビューしていただけると
=> Generate models #26

.gitignore, Gemfile, Gemfile.lock, db/schema.rb
Macなら
`$brew install graphviz`
し、プロジェクトのルートで
`$rake erd`
でプロジェクトのルートにerd.pdfというファイル名でモデル依存関係図が出力される。
=> add rails-erd and update gitiignore

.editorconfig
#34
Please see http://editorconfig.org/
=> Add .editorconfig for Ruby, Rails, TypeScript, React and so on. Close #34

db/schema.rb, test/fixtures/problems.yml, test/fixtures/submissions.yml, test/fixtures/users.yml, test/models/contest_test.rb, wercker.yml
=> Set up wercker (CI service). Close #33

app/models/data_set.rb, app/models/submission.rb, app/models/test_case.rb, db/migrate/20170214103526_rename_test_cases_to_data_sets.rb, db/schema.rb, test/fixtures/admins.yml, test/fixtures/data_sets.yml, test/fixtures/submissions.yml
`TestCase` テーブルを `DataSet` テーブルに変更しました。
=> Rename TestCase to DataSet

db/migrate/20170217124715_change_foreign_key_to_null_false.rb, db/schema.rb
=> Disable null foreign key. Close #46

.gitignore, app/assets/javascripts/application.js, app/views/react_tutorial/index.html.erb, config/initializers/assets.rb, package.json, src/tutorial/index.tsx, tsconfig.json, webpack.config.js
WebpackでビルドしたファイルをSprockets通すことにした
=> Change webpack config

app/controllers/api/contests/submissions_controller.rb, app/controllers/api/contests_controller.rb, config/routes/user.rb, spec/spec_helper.rb
=> Spec Configuration

Gemfile, Gemfile.lock, spec/controllers/admin/contests_controller_spec.rb, spec/rails_helper.rb, spec/spec_helper.rb, spec/support/factory_girl.rb, test/controllers/admin/contests_controller_test.rb
This PR is incomplete for #75 
I'd like to disable flaky tests because they obviously obstruct our development...
=> Add a simple test case. Update dependencies.

app/controllers/admin/problems_controller.rb
=> 問題一覧ページから、未ログインの管理者をリダイレクトする

app/assets/stylesheets/application.scss, app/assets/stylesheets/contests.scss, app/views/contests/show.html.erb, config/initializers/assets.rb, src/contests/ContestApp.tsx, src/contests/ContestHome.tsx, src/contests/ContestShow.tsx
React-Component-ContestShow Added
All related files have been isolated into a new branch for pull request
Please review
=> React-Component-ContestShow Added

app/controllers/api/contests_controller.rb, app/models/contest.rb, app/models/data_set.rb, app/models/problem.rb, app/models/submission.rb, db/migrate/20170307182321_change_judge_status_id_to_judge_status.rb, db/migrate/20170307182503_change_language_id_to_language.rb, db/schema.rb, lib/tasks/generate_sample_data.rake, spec/controllers/api/contests_controller_spec.rb, test/fixtures/submissions.yml
React側とうまく噛み合うように微修正
migrationなども入っているので早めにマージしたい
=> fix api/contests

config/application.rb
=> Set default time zone to Tokyo

src/contests/ContestApp.tsx
=> fix submit results error #152

app/assets/stylesheets/contests.scss, app/views/layouts/application.html.erb, src/contests/Navigation.tsx
=> Icons for solved data set #141

app/views/admin/contests/_form.html.erb
Enable to input multi-line descriptions.
=> Change text_field to text_area

app/controllers/api/contests_controller.rb, app/controllers/api/submissions_controller.rb, spec/controllers/api/contests_controller_spec.rb, src/contests/Navigation.tsx
=> Fix ranking bug #175

app/assets/stylesheets/variables.scss
=> change brand-color

app/assets/javascripts/data_sets.coffee, app/assets/stylesheets/data_sets.scss, app/controllers/data_sets_controller.rb, app/helpers/data_sets_helper.rb, config/routes/user.rb, spec/controllers/contests_controller_spec.rb, spec/controllers/data_sets_controller_spec.rb, spec/factories/contests.rb, spec/helpers/data_sets_helper_spec.rb, src/contests/Problem.tsx
前回出したプルリクのrubocop修正がひどかったので、もう一度ブランチ切って作り直しました
データセットをダウンロードできるようにメソッドを追加しました
=> Feature/issue 179  Create data set download 

app/controllers/api/submissions_controller.rb, spec/controllers/api/submissions_controller_spec.rb
=> Enable submission judge #191

app/controllers/data_sets_controller.rb, app/models/data_set.rb, spec/controllers/data_sets_controller_spec.rb, spec/models/data_set_spec.rb
=> Unify new line code #211

app/assets/stylesheets/markdown.scss, app/assets/stylesheets/pages/contests.scss, app/controllers/api/contests_controller.rb, app/models/data_set.rb, spec/controllers/api/contests_controller_spec.rb, src/contests/ContestApp.tsx, src/contests/ContestHome.tsx, src/contests/ContestObject.tsx, src/contests/DataSetObject.tsx, src/contests/DataSetScoreObject.tsx, src/contests/Navigation.tsx, src/contests/Problem.tsx, src/contests/ProblemObject.tsx, src/contests/Ranking.tsx
Close #209 
Close #207 
Close #193 
Close #142
コンテストページを全体的に手直ししました
(ごめんなさい、PR分けようと思ったのですが一緒に直しちゃいました)
=> Improve contests#show page #209 #207 #193 #142

src/contests/Problem.tsx
=> change button name

Gemfile.lock
=> modify Gemfile.lock

app/views/users/registrations/new.html.erb
Close #240 
HTML5のフォームバリデーションでxxx.waseda.jp以外のメールアドレスでは登録できないようにした
**まだmasterにマージしないでください**
=> Add mail address validation #240

app/controllers/admin/contests_controller.rb, app/views/admin/contests/json_upload.html.erb, app/views/admin/contests/show.html.erb, config/routes/admin.rb, spec/controllers/admin/contests_controller_spec.rb, spec/factories/users.rb
=> コンテスト情報のJSONアップロード

Gemfile, Gemfile.lock, spec/factories/admin_roles.rb, spec/factories/contest_registrations.rb, spec/factories/contests.rb, spec/factories/data_sets.rb, spec/factories/editorials.rb, spec/factories/problems.rb, spec/factories/submissions.rb, spec/factories/users.rb, spec/support/factory_girl.rb
Factory GirlがFactory Botに変わったらしいのでGemfileを更新した。
参考: [【翻訳】"Factory Girl"が"Factory Bot"に変わった理由（と移行手順） - Qiita](https://qiita.com/jnchito/items/c71b8f66f61214227555)
@getty104 @musaprg @Shikugawa @rdrgn 
全然急ぎじゃないので都合が良さそうな時に見ておいてもらえると
=> Replace FactoryGirl with FactoryBot

src/contests/Problem.tsx
提出するテキストボックスに最初に表示されている説明文の修正．
データセットがSmall / Largeの2種類とは限らなくなったので．
=> Fix message on submission textbox

package.json
=> fix pre-build

.dockerignore, Dockerfile-rails, docker-compose.yml
- enable gems cacheing
- use docker volume
- install specific version of Node.js
=> Docker Cleanup

app/controllers/admin/awards_controller.rb
- FastACの算出順を逆にしました（難しい方から算出する）
- Rankingを6位までにした
=> Hotfix awards order

app/assets/stylesheets/reset.scss, app/views/layouts/application.html.erb
=> Update katex version
